[project]
name = "uv-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["note-mcp", "check-xml-table", "mcp-ai-review", "mcp-anki-maker"]
