[project]
name = "mcp-anki-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "openai>=1.70.0",
    "requests>=2.32.3",
]
